trigger:
  - master

resources:
  repositories:
    - repository: pipelineTemplateRepository
      type: github
      name: emmanuelbenitez/Be.Stateless.Build.Agent.Yaml.Pipeline.Templates
      ref: refs/heads/dev/support-hybrid-pwsh
      endpoint: github.com_icraftsoftware

extends:
  template: Pipelines/pwsh/continuous-integration.yml@pipelineTemplateRepository
  parameters:
    Major: 1
    Minor: 0
    SkipTest: false
